{{ if .Values.shared.async.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "limina.fullname" . }}-async
  namespace: {{ .Release.Namespace }}
  {{- with .Values.shared.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.shared.pvc.accessModes }}
  storageClassName: {{ include "limina.fullname" . }}-async
  resources:
    requests:
      storage: {{ .Values.shared.pvc.storage }}
{{- end }}
