# Select a cloud provider. Must be one of "Azure", "AWS", or "Other"
cloudProvider: "AWS"

# Override the default name of the application, used in the helper script to populate things like selector labels
nameOverride: ""
# Override the full name of the application
fullnameOverride: ""

# This section contains information shared across Limina products
shared:
  # Limina repository
  repository: "crprivateaiprod.azurecr.io"

  # This secret will store your docker pull credentials. You can obtain these from the customer portal
  # If you enable the External Secrets Operator, this section will be ignored
  imagePullSecrets:
    name: &imagePullSecretsName "crprivateaiprod-creds"

  # Settings for the Limina license file
  license:
    # If you enable the External Secrets Operator, this section will be ignored
    # Sets the name of the license secret object
    name: "limina-license"
    # Add optional annotations for the license secret. For more details see https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    annotations: {}
    # Example annotations
    # annotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value2"
    volumeMount: "license-volume"
    # If you use the External Secrets Operator, you can ignore this setting as the license file will be populated via a secret
    # Override with your license data. See readme for more details
    data: '{"id": "1", "tier": "..."}'


# This section contains all information related to the Limina core product
core:
  # This section contains configuration for the kubernetes service for the core product
  service:
    # Set the type for the service
    type: "ClusterIP"
    # Set the port for the service
    port: 80
    # Set the target port for the deployment
    targetPort: &coreTargetPort 8080
    # Add custom annotations to the service
    annotations: {}
    # Set the Azure load balancer to be internal only, if you are planning to use an ingress to manage traffic
    # annotations:
    #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # Set the AWS load balancer to be internal only, if you are planning to use an ingress to manage traffic
    # annotations:
    #   service.beta.kubernetes.io/aws-load-balancer-internal: "true"

  # Configuration related to the deployment
  deployment:
    # Sets the number of replicas for the Limina deployment
    replicaCount: 1

    image:
      name: "deid"
      pullPolicy: "IfNotPresent"
      # Can be a direct version tag / container flavour (i.e. 4.0.4-cpu-text) OR a 'latest' tag (i.e. cpu, cpu-text, gpu, gpu-text)
      # It is recommended to pin to a specific version for production environments
      tag: "4.4.1-cpu"

    # Add custom additional mounts
    additionalMounts: {}
    # Example mount configuration from a secret
    # additionalMounts:
    #   volumeMounts:
    #     - name: "mount-name"
    #       mountPath: "/mount/path"
    #   volumes:
    #     - name: "mount-name"
    #       secret:
    #         secretName: "mount-secret"

    # Add custom pod annotations to the deployment
    podAnnotations: {}
    # Example annotations
    # podAnnotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value1"

    # These are the values for liveness, startup and readiness probes.
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#probe-v1-core
    livenessProbe: {}
    # Example livenessProbe. This is not recommended as it may cause pod instability
    # livenessProbe:
    #   httpGet:
    #     path: "/healthz"
    #     port: *coreTargetPort
    #     scheme: "HTTP"
    #   initialDelaySeconds: 60
    #   periodSeconds: 60
    #   failureThreshold: 30
    #   timeoutSeconds: 1
    startupProbe:
      # Note: You should expect to see warnings for startup probe failures in the pod events until the container starts
      httpGet:
        path: "/healthz"
        port: *coreTargetPort
        scheme: "HTTP"
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 23
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: "/healthz"
        port: *coreTargetPort
        scheme: "HTTP"
      initialDelaySeconds: 60
      periodSeconds: 20
      failureThreshold: 3
      timeoutSeconds: 1

    # These are the values for the affinity
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#volumenodeaffinity-v1-core
    nodeAffinity:
      values: {}
      # Use the following to example to attempt to schedule nodes first on nodes with the label "limina-spot"
      # and after on nodes with the label "limina"
      # values:
      #   preferredDuringSchedulingIgnoredDuringExecution:
      #     - preference:
      #         matchExpressions:
      #           - key: "nodetype"
      #             operator: "In"
      #             values:
      #               - "limina"
      #       weight: 1
      #     - preference:
      #         matchExpressions:
      #           - key: "nodetype"
      #             operator: "In"
      #             values:
      #               - "limina-spot"
      #       weight: 100

    podAntiAffinity:
      # Recommended configuration to ensure only one Limina container is scheduled per node:
      values:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: "In"
                  values:
                    - "limina"
                - key: "app.kubernetes.io/instance"
                  operator: "In"
                  values:
                    - "limina"

    topologySpreadConstraints:
      values: []
      # Use the following if you would like to spread your pods evenly across your infrastructure zones
      # values:
      #   - labelSelector:
      #       matchLabels:
      #         app.kubernetes.io/name: "limina"
      #         app.kubernetes.io/instance: "limina"
      #     matchLabelKeys:
      #       - "pod-template-hash"
      #     maxSkew: 1
      #     topologyKey: "topology.kubernetes.io/zone"
      #     whenUnsatisfiable: "ScheduleAnyway"

    tolerations:
      values: []
      # Use the following if you have added a taint to your nodes of app=limina
      # values:
      #   - key: app
      #     operator: "Equal"
      #     value: "limina"
      #     effect: "NoSchedule"

    # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
    limits: {}
    # Use the following if you would like to add limits to the core product
    # limits:
    #   memory: "12Gi"
    #   cpu: "4"

    requests: {}
    # Use the following if you would like to add requests to the core product
    # requests:
    #   memory: "8Gi"
    #   cpu: "3"

  # Enter any environment variables for your deployment. You can find the list at https://docs.getlimina.ai/configuration-and-operations/container-management/environment-variables
  configmap:
    values: []
    # Example environment variables:
    # values:
    #   - PAI_DISABLE_RAM_CHECK: "true"

  # Specifies whether to deploy the kubernetes core ingress
  # Requires haproxy-ingress and cert-manager to be installed
  ingress:
    # Enable or disable the ingress configuration
    enabled: false
    # Set the class to handle the ingress traffic. Default to haproxy
    ingressClassName: "haproxy"
    # Set your own custom annotations, see https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/ingress/
    annotations: {}
    # Example to rate limit to 15 requests per minute
    # annotations:
    #   haproxy.org/rate-limit-requests: 15
    #   haproxy.org/rate-limit-period: "1m"
    # Provision selfsigned certificates by default via cert-manager. Change if you wish to customize
    selfsigned: true
    # Replace this with the domain name for the ingress
    host: "ingress.domain.com"
    tlsSecretName: "limina-tls"

  # These secrets will be added to the environment variables for the Limina core deployment
  # If you use the External Secrets Operator, this section will be ignored
  secrets:
    # Add optional annotations for the deployment secret. For more details see https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    annotations: {}
    # Example annotations
    # annotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value2"
    # If you use the External Secrets Operator, you can ignore this section and populate via the externalsecrets section below
    values: []
    # Enter any environment variables for your deployment you wish to remain secret. Example: https://docs.getlimina.ai/configuration-and-operations/advanced-features/azure-ocr
    # values:
    #   - name: "PAI_AZ_COMPUTER_VISION_KEY"
    #     value: "keyvalue"

# Configuration for the External Secrets operator
externalsecrets:
  # Specifies whether to use configuration for the external secrets operator
  enabled: false
  # Specifies the secret store to retrieve secrets
  secretstorename: "secret-store"
  # Configuration details for the docker credentials secret
  dockercredential:
    # Optional annotations for the docker credential externalsecret and secret objects
    annotations: {}
    # Example annotations
    # annotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value2"
    # Set the refresh interval to check for updated secrets
    refreshInterval: "1h"
    # This is the reference to the name of the secret from the secret store
    # For simplicity, it is assumed that all the credentials are in the same key, in different properties
    remoteRefKey: *imagePullSecretsName
    serverProperty: "server"
    usernameProperty: "username"
    passwordProperty: "password"
  # Configuration details for the license file
  license:
    # Optional annotations for the license externalsecret and secret objects
    annotations: {}
    # Example annotations
    # annotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value2"
    # Set the refresh interval to check for updated secrets
    refreshInterval: "1h"
    # This is the reference to the name of the secret from the secret store
    remoteRefKey: "license"
    licenseProperty: "license.json"
  # Configuration for the optional Limina environment secrets
  secrets:
    # Enables or disables Limina environment secrets
    enabled: false
    # Optional annotations for the deployment externalsecret and secret objects
    annotations: {}
    # Example annotations
    # annotations:
    #   annotation-key1: "annotation-value1"
    #   annotation-key2: "annotation-value2"
    # Set the refresh interval to check for updated secrets
    refreshInterval: "1h"
    # This is the reference to the name of the secret from the secret store
    # All properties will be added from the secret in the secret store to the container environment variables
    remoteRefKey: "limina-core"
