{{- if .Values.shared.async.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "limina.fullname" . }}-custodian
  namespace: {{ .Release.Namespace }}
  {{- with .Values.custodian.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  type: {{ .Values.custodian.service.type }}
  ports:
    - port: {{ .Values.custodian.service.port }}
      targetPort: {{ .Values.custodian.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.custodian.deployment.selector.matchLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
