{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.core.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "limina.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalSecrets.core.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecrets.core.refreshInterval }}
  target:
    name: {{ include "limina.fullname" . }}-core
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.core.remoteRefKey }}
{{- end }}
