apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "limina.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.core.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "limina.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.core.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "limina.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.shared.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.shared.repository }}/{{ .Values.core.deployment.image.name }}:{{ .Values.core.deployment.image.tag }}"
          {{- if or .Values.core.deployment.limits .Values.core.deployment.requests .Values.core.deployment.gpuEnabled }}
          resources:
            {{- if or .Values.core.deployment.limits .Values.core.deployment.gpuEnabled }}
            limits:
              {{- if .Values.core.deployment.gpuEnabled }}
              nvidia.com/gpu: 1
              {{- end }}
            {{- with .Values.core.deployment.limits }}
              {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- end }}
            {{- with .Values.core.deployment.requests }}
            requests:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.core.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "limina.fullname" . }}-core
                optional: true
          envFrom:
            - secretRef:
                name: {{ include "limina.fullname" . }}-core
                optional: true
          volumeMounts:
            - name: {{ .Values.core.deployment.license.volumeMount }}
              mountPath: /app/license
              {{- with .Values.core.deployment.additionalMounts.volumeMounts }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
          {{- if .Values.core.deployment.gpuEnabled }}
            - name: dshm-volume
              mountPath: /dev/shm
          {{- end }}
          {{- with .Values.core.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.core.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.core.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ .Values.core.deployment.license.volumeMount }}
          secret:
            {{- if .Values.externalsecrets.enabled }}
            secretName: {{ .Values.externalsecrets.license.name }}
            {{- else }}
            secretName: {{ .Values.core.deployment.license.name }}
            {{- end }}
          {{- with .Values.core.deployment.additionalMounts.volumes }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- if .Values.core.deployment.gpuEnabled }}
        - name: dshm-volume
          emptyDir:
            medium: Memory
      {{- end }}

      {{- if or .Values.core.deployment.nodeAffinity.values .Values.core.deployment.podAntiAffinity.values }}
      affinity:
        {{- with .Values.core.deployment.nodeAffinity.values }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.core.deployment.podAntiAffinity.values }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      
      {{- with .Values.core.deployment.topologySpreadConstraints.values }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.core.deployment.tolerations.values }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
