{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.shared.license.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.shared.license.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
data:
  license.json: |-
{{- .Values.shared.license.data | b64enc | nindent 4 }}
{{- end }}
