apiVersion: v1
kind: Service
metadata:
  name: {{ include "limina.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  {{- with .Values.core.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: {{ .Values.core.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "limina.selectorLabels" . | nindent 4 }}
