{{- if and .Values.externalsecrets.enabled .Values.externalsecrets.api.enabled .Values.shared.async.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "limina.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalsecrets.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretstorename }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalsecrets.api.refreshInterval }}
  target:
    name: {{ include "limina.fullname" . }}-core
  dataFrom:
    - extract:
        key: {{ .Values.externalsecrets.api.remoteRefKey }}
{{- end }}
