{{- if and (not .Values.externalsecrets.enabled) .Values.shared.async.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "limina.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  {{- with .Values.api.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
data:
{{- range .Values.api.secrets.data }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
