{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.tlsApi.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "limina.fullname" . }}-tls-api
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalSecrets.tlsApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecrets.tlsApi.refreshInterval }}
  target:
    name: {{ .Values.api.ingress.tlsSecretName }}
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ `{{ .tlsSecret | pkcs12cert }}` }}"
        tls.key: "{{ `{{ .tlsSecret | pkcs12key }}` }}"
  data:
    - secretKey: tlsSecret
      remoteRef:
        key: {{ .Values.externalSecrets.tlsApi.remoteRefKey }}
{{- end }}
