{{- if not .Values.externalsecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "limina.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.core.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
data:
{{- range .Values.core.secrets.values }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
