{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.shared.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalSecrets.dockerCredential.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecrets.dockerCredential.refreshInterval }}
  target:
    name: {{ .Values.shared.imagePullSecrets.name }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ `{{ .registryHost }}` }}":{"username":"{{ `{{ .registryUsername }}` }}", "password":"{{ `{{ .registryPassword }}` }}", "auth": "{{ `{{ printf "%s:%s" .registryUsername .registryPassword | b64enc }}` }}"}}}'
  data:
    - secretKey: registryHost
      remoteRef:
        key: {{ .Values.externalSecrets.dockerCredential.remoteRefKey }}
        property: {{ .Values.externalSecrets.dockerCredential.serverProperty }}
    - secretKey: registryUsername
      remoteRef:
        key: {{ .Values.externalSecrets.dockerCredential.remoteRefKey }}
        property: {{ .Values.externalSecrets.dockerCredential.usernameProperty }}
    - secretKey: registryPassword
      remoteRef:
        key: {{ .Values.externalSecrets.dockerCredential.remoteRefKey }}
        property: {{ .Values.externalSecrets.dockerCredential.passwordProperty }}
{{- end }}
