{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.shared.license.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.externalSecrets.license.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "limina.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecrets.license.refreshInterval }}
  target:
    name: {{ .Values.shared.license.name }}
  data:
    - secretKey: license.json
      remoteRef:
        key: {{ .Values.externalSecrets.license.remoteRefKey }}
        property: {{ .Values.externalSecrets.license.licenseProperty }}
{{- end }}
